# hardcoded list of paths to exclude while we incrementally lint codebase
# See issue #4347 for tracking
 exclude = [
    "src/sta/",
]

ignore = [
    "unbraced-expr",
]

[style]
indent = 2
line-length = 100
allow-aligned-sets = true
indent-namespace-eval = false
spaces-in-braces = true
