# hardcoded list of paths to exclude while we incrementally lint codebase
# See issue #4347 for tracking
 exclude = [
    "src/sta/",
    "src/ant/test/",
    "src/cts/test/",
    "src/dbSta/test/",
    "src/dft/test/",
    "src/dpl/test/",
    "src/drt/test/",
    "src/dst/test/",
    "src/fin/test/",
    "src/gpl/test/",
    "src/grt/etc/scripts/",
    "src/grt/test/",
    "src/ifp/test/",
    "src/mpl/test/",
    "src/odb/",
    "src/par/examples/",
    "src/par/test/",
]

ignore = [
    "unbraced-expr",
]

[style]
indent = 2
line-length = 100
allow-aligned-sets = true
indent-namespace-eval = false
spaces-in-braces = true
