name: Check that OK files are up to date

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  format:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check ok files
        run: |
          find -name "*.ok" | xargs grep -n "Differences found " > diffs
          cat diffs
          if [ -s diffs ]; then
            exit 1
          fi
